"""Init

Revision ID: 6dba3417da66
Revises: 6d2c1d662fe7
Create Date: 2024-07-23 15:26:29.441393

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '6dba3417da66'
down_revision: Union[str, None] = '6d2c1d662fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    rates_table = table(
        "rates",
        column("id", sa.Integer()),
        column("rate_name", sa.String()),
        column("price", sa.Float()),
        column("created_at", sa.DateTime()),
        column("updated_at", sa.DateTime())
    )
    op.bulk_insert(rates_table,
                   [
                       {
                           "id": 1,
                           "rate_name": "standard",
                           "price": 40.0,
                           "created_at": datetime.now(),
                           "updated_at": datetime.now()
                       }
                   ],
                   )
    op.add_column('users', sa.Column('rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rates', ['rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'rate_id')
    op.drop_table('rates')
    # ### end Alembic commands ###
