"""Init

Revision ID: d8fbc36fbca2
Revises: d152008ee666
Create Date: 2024-07-20 17:08:39.566324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fbc36fbca2'
down_revision: Union[str, None] = 'd152008ee666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('banned', sa.Boolean(), nullable=False))
    op.drop_column('cars', 'baned')
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    op.add_column('cars', sa.Column('baned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('cars', 'banned')
    # ### end Alembic commands ###
